% Startup
%

addpath( '~/Documents/PhD/dev.matlab/', '~/Documents/PhD/macrosight/', ...
        '~/Documents/PhD/matlab.anglegram/', ...
        '~/Documents/PhD/matlab.manualSegmentation/',...
        '~/Documents/PhD/matlab.thresholding/', ...
        '~/Documents/PhD/matlab.utils/', ...
        '~/Documents/PhD/phagosight/');

cd('~/Documents/PhD/SW');
disp('Done startup routine.')
